version: '3.9'

networks:
  prosumers:
    name: prosumers
    external: true

  vaidyuti-public:
    name: vaidyuti-public
    external: true

services:
  prosumer:
    build: .
    scale: 10
    environment:
      PROFILE_ENDPOINT: http://dispatcher/api/retrieve
      VAIDYUTI_MQTT_SERVER: emqx
    command: python main.py
    volumes:
      - .:/app
    networks:
      - prosumers
      - vaidyuti-public
